name: cicd-v2

on:
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      dir: ${{ steps.set-dirs.outputs.dir }}
    steps:
      - run: sudo apt-get update && sudo apt-get install --yes jq
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - id: set-dirs
        run: |
          DIRS=$(
            find ./src -maxdepth 2 -type f -name "main.tf" -print0 \
              | xargs -0 -n1 dirname \
              | sort --unique \
              | jq --raw-input --compact-output --slurp 'split("\n")[:-1]'
          )
          echo ::set-output name=dir::$DIRS
  loop:
    needs: [setup]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: ${{ fromJSON(needs.setup.outputs.dir) }}
    steps:
      - run: echo ${{ matrix.dir }}
